### ISSUE TITLE
What is \mathcal{D} in the Bayesian statistics section?

### ISSUE THREAD

**Issue by DustinWehr** [StatProofBook/StatProofBook.github.io#105]
It appears together with the unexplained `~` in the [very first definiton](https://statproofbook.github.io/D/gm) of that section, and I'm left feeling like I've been transported from happy precise math land to a machine learning conference paper.

**Comment by JoramSoch** [comment]
@DustinWehr: Sorry for the inaccuracies! In statistical literature, the tilde `~` is usually read as "is distributed as" or "follows the distribution". Consequently, `\mathcal{D}(\theta)` refers to "a probability distribution parametrized by θ". This follows the practice of denoting probability distributions with caligraphed letters (e.g. `\mathcal{N}(0,1)`), but avoids restricting generative models to only specific distributions (e.g. Gaussian). Also see this [incomplete list of suggested notation](https://github.com/StatProofBook/StatProofBook.github.io/wiki/Suggested-Notation).

I'd suggest the following: We link the word "distribution" in `D/gm` to the [definition "Probability Distribution"](https://statproofbook.github.io/D/dist) and add a clarifying after-sentence such as "where `\mathcal{D}` denotes an arbitrary probability distribution and `\theta` are the parameters of this distribution". What do you think?

**Comment by DustinWehr** [comment]
That helps. I think what throws me off is that this definition seems to be mixing a number of things:
(1). A simple exact math definition. As far as I can tell, the usage/importance-independent, exact part of a "generative model" is a triple <S, y, D> where S is a set, y is in S, and D is a function that maps some parameter domain to probability distributions on S. One could call it a "generative model structure" (not a serious suggestion).
(2). Some preliminary information about how this is used in practice. For example, what concepts/assumptions are we importing when we refer to a "generative model structure" as a "generative model"?
(3). Notation definition `m: y ~ D(theta)`.

A style I've seen used for (1) in cs theory, that avoids introducing an extra name like "generative model structure", is: "A generative model is, first of all, a triple...". One could then follow up with (2), and leave (3) till the very end.

**Comment by DustinWehr** [comment]
Actually, as I was just trying to write out a candidate for (2), I realized it's unclear to me if D(theta) is supposed to denote:
(a) A family of distributions, where theta is used for the family-indexing variable, or 
(b) A single distribution that came from an unnamed family of distributions. In that case, theta is an unknown constant

**Comment by JoramSoch** [comment]
@DustinWehr: I see your point, but I fear that a lot of definitions have to be rewritten in this archive then.

First, regarding your second question: In a generative model, θ has a fixed value, but is unknown. That is, a generative model specifies a single distribution, but the parameters of this distribution are not known and have to be estimated. (There might be exceptions to this (e.g. multi-level/hierarchical models), but there is always something constant at the bottom (i.e. the last latent parameters in the chain), so that these "exceptions" can probably also be handled with this definition.)

Second, regarding your first point: [Currently](https://github.com/StatProofBook/StatProofBook.github.io/blob/fd005b6399c8d4ea91b447adff2694c25dbb946e/D/gm.md), the tupel is implicitly refered to by saying that a generative model is based on "measured data y", "latent parameters θ" and "a distribution of y given θ". It's true that S (such that `y \in S`) is not mentioned which is - again - because generative models are not restricted to specific sets of data. The idea would be that specific generative models mention (i) type of data and (ii) distribution, such that the distribution implies which set the data are in (because each probability distribution has a specific domain). Examples: [binomial observations](https://statproofbook.github.io/D/bin-data), [Poisson-distributed data](https://statproofbook.github.io/D/poiss-data), [multiple linear regression](https://statproofbook.github.io/D/mlr).

Now the queston is: Do we want the definition to start by "a generative model specifies a probability distribution of y given θ" or by "a generative model is a triple <S, y, D> where S is a set, y is in S, and D is a function that ...". To me, the first option is more intuitive (and I guess it would be to an empirical researcher interested in data analysis), but I think the CS-style of writing you suggested is a nice compromise between mathematical precision and clarity for non-mathematicians.

**Comment by JoramSoch** [comment]
One more thing: On the long run, it is intended that there are also definitions of "measured data" and "latent parameters" (not yet linked to other pages in the archive). The idea is that all this information together then sufficiently defines "generative model" (similarly for other definitions in the archive) and the reader has access to the combined information by clicking on the links, as needed. I believe, part of what you write in (1) would be covered in a definition of "measured data" and part of what you write in (2) would be covered in a definition of "latent parameters".

**Comment by JoramSoch** [comment]
Resolved with commits [ae2b671](https://github.com/StatProofBook/StatProofBook.github.io/commit/ae2b6714cf97ac9e06cf1094aeb2a9f212570d7e) and [024d898](https://github.com/StatProofBook/StatProofBook.github.io/commit/024d89826d239a4e6b2b44cc220bc0fb7fbb2b3d).
